modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="http://www.github.com/MelanX/curse-of-curses/issues/"

[[mods]]
modId="curseofcurses"
version="${file.jarVersion}"
displayName="Curse of Curses"
updateJSONURL="https://raw.githubusercontent.com/MelanX/curse-of-curses/1.14/update/update.json"
displayURL="www.curseforge.com/members/melanx/"
#logoFile="examplemod.png"
credits="InQuognito for the idea on Darkhax' Cursed mod issue 7 on GitHub."
authors="MelanX"
description='''
A mod which applies a random curse with a configurable chance each night to a random enchantable item in players inventory.
'''

[[dependencies.curseofcurses]]
    modId="forge"
    mandatory=true
    versionRange="[28.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.curseofcurses]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
