modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://www.github.com/MelanX/curse-of-curses/issues/"
license="MIT License"

[[mods]]
modId="curseofcurses"
version="${version}"
displayName="Curse of Curses"
updateJSONURL="https://assets.melanx.de/updates/curse-of-curses.json"
displayURL="www.curseforge.com/members/melanx/"
credits="InQuognito for the idea on Darkhax' Cursed mod issue 7 on GitHub."
authors="MelanX"
description='''
A mod which applies a random curse with a configurable chance each night to a random enchantable item in players inventory.
'''

[[dependencies.curseofcurses]]
    modId="forge"
    mandatory = true
    versionRange = "[45.0.1,)"
    ordering = "NONE"
    side="BOTH"

[[dependencies.curseofcurses]]
    modId="minecraft"
    mandatory = true
    versionRange = "[1.19.4, 1.20)"
    ordering = "NONE"
    side="BOTH"
