modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod.license}"
issueTrackerURL = "${mod.issue_url}"

[[mods]]
modId = "${mod.modid}"
version = "${mod.version}"
displayURL = "${mod.source_url}"
displayName = "Curse of Curses"
updateJSONURL = "https://assets.melanx.de/updates/curse-of-curses.json"
authors = "MelanX"
description = """
A mod which applies a random curse with a configurable chance each night to a random enchantable item in players inventory.
"""

[[dependencies.${ mod.modid }]]
   modId = "neoforge"
   type = "required"
versionRange = "[${mod.neoforge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod.modid }]]
modId = "minecraft"
type = "required"
versionRange = "[${mod.minecraft},)"
ordering = "NONE"
side = "BOTH"
