modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${license}"
issueTrackerURL="https://github.com/ChaoticTrials/CurseOfCurses/issues"

[[mods]]
modId="${modid}"
version="${mod_version}"
displayName="Curse of Curses"
updateJSONURL="https://assets.melanx.de/updates/curse-of-curses.json"
displayURL="https://modrinth.com/user/MelanX"
authors="MelanX"
description="""
A mod which applies a random curse with a configurable chance each night to a random enchantable item in players inventory.
"""

[[dependencies.${modid}]]
   modId = "neoforge"
   type = "required"
   versionRange = "[${neo_version},)"
   ordering="NONE"
   side="BOTH"

[[dependencies.${modid}]]
   modId="minecraft"
   type="required"
   versionRange="[${minecraft_version},)"
   ordering="NONE"
   side="BOTH"
